paths:
    tests: .tests/php
    output: .codeception/_output
    data: .codeception/_data
    support: .codeception/_support
    envs: .codeception/_envs
actor_suffix: SpiralGrafana
extensions:
    enabled:
        - Codeception\Extension\RunFailed
params:
    - env
    - .codeception/_config/params.php
settings:
    backup_globals: false
coverage:
    enabled: true
    low_limit: 20
    high_limit: 60
    show_only_summary: false
    include:
        - ./src/*
